name: Compile binaries to WASM
on:
  release:
    types: [published]
jobs:
  compile-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mymindstorm/setup-emsdk@v11
        with:
          version: 3.1.20
          actions-cache-folder: "/emsdk-cache"
      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
        with:
          version: 1.10.0
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.12
      - name: "Compile WASM"
        run: make compile
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: "Publish package"
        run: npm i && npm run release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
